export interface Country {
  name: string;
  code: string;
  dial_code: string;
  emoji: string;
  maxLength: number;
}

export const COUNTRIES: Country[] = [
  { name: 'Angola', code: 'AO', dial_code: '+244', emoji: '🇦🇴', maxLength: 9 },
  { name: 'Portugal', code: 'PT', dial_code: '+351', emoji: '🇵🇹', maxLength: 9 },
  { name: 'United Kingdom', code: 'GB', dial_code: '+44', emoji: '🇬🇧', maxLength: 10 },
  { name: 'China', code: 'CN', dial_code: '+86', emoji: '🇨🇳', maxLength: 11 },
  { name: 'United States', code: 'US', dial_code: '+1', emoji: '🇺🇸', maxLength: 10 },
  { name: 'Brazil', code: 'BR', dial_code: '+55', emoji: '🇧🇷', maxLength: 11 },
  { name: 'Canada', code: 'CA', dial_code: '+1', emoji: '🇨🇦', maxLength: 10 },
  { name: 'France', code: 'FR', dial_code: '+33', emoji: '🇫🇷', maxLength: 9 },
  { name: 'Germany', code: 'DE', dial_code: '+49', emoji: '🇩🇪', maxLength: 11 },
  { name: 'Italy', code: 'IT', dial_code: '+39', emoji: '🇮🇹', maxLength: 10 },
  { name: 'Spain', code: 'ES', dial_code: '+34', emoji: '🇪🇸', maxLength: 9 },
  { name: 'India', code: 'IN', dial_code: '+91', emoji: '🇮🇳', maxLength: 10 },
  { name: 'Japan', code: 'JP', dial_code: '+81', emoji: '🇯🇵', maxLength: 10 },
  { name: 'Australia', code: 'AU', dial_code: '+61', emoji: '🇦🇺', maxLength: 9 },
  { name: 'South Africa', code: 'ZA', dial_code: '+27', emoji: '🇿🇦', maxLength: 9 },
  { name: 'Nigeria', code: 'NG', dial_code: '+234', emoji: '🇳🇬', maxLength: 10 },
  { name: 'Egypt', code: 'EG', dial_code: '+20', emoji: '🇪🇬', maxLength: 10 },
  { name: 'Kenya', code: 'KE', dial_code: '+254', emoji: '🇰🇪', maxLength: 9 },
  { name: 'Morocco', code: 'MA', dial_code: '+212', emoji: '🇲🇦', maxLength: 9 },
  { name: 'Ghana', code: 'GH', dial_code: '+233', emoji: '🇬🇭', maxLength: 9 },
  { name: 'Senegal', code: 'SN', dial_code: '+221', emoji: '🇸🇳', maxLength: 9 },
  { name: 'Ivory Coast', code: 'CI', dial_code: '+225', emoji: '🇨🇮', maxLength: 10 },
  { name: 'Cameroon', code: 'CM', dial_code: '+237', emoji: '🇨🇲', maxLength: 9 },
  { name: 'Ethiopia', code: 'ET', dial_code: '+251', emoji: '🇪🇹', maxLength: 9 },
  { name: 'Tanzania', code: 'TZ', dial_code: '+255', emoji: '🇹🇿', maxLength: 9 },
  { name: 'Uganda', code: 'UG', dial_code: '+256', emoji: '🇺🇬', maxLength: 9 },
  { name: 'Algeria', code: 'DZ', dial_code: '+213', emoji: '🇩🇿', maxLength: 9 },
  { name: 'Sudan', code: 'SD', dial_code: '+249', emoji: '🇸🇩', maxLength: 9 },
  { name: 'Mozambique', code: 'MZ', dial_code: '+258', emoji: '🇲🇿', maxLength: 9 },
  { name: 'Madagascar', code: 'MG', dial_code: '+261', emoji: '🇲🇬', maxLength: 9 },
  { name: 'Mexico', code: 'MX', dial_code: '+52', emoji: '🇲🇽', maxLength: 10 },
  { name: 'Argentina', code: 'AR', dial_code: '+54', emoji: '🇦🇷', maxLength: 10 },
  { name: 'Chile', code: 'CL', dial_code: '+56', emoji: '🇨🇱', maxLength: 9 },
  { name: 'Colombia', code: 'CO', dial_code: '+57', emoji: '🇨🇴', maxLength: 10 },
  { name: 'Peru', code: 'PE', dial_code: '+51', emoji: '🇵🇪', maxLength: 9 },
  { name: 'Venezuela', code: 'VE', dial_code: '+58', emoji: '🇻🇪', maxLength: 10 },
  { name: 'Russia', code: 'RU', dial_code: '+7', emoji: '🇷🇺', maxLength: 10 },
  { name: 'Ukraine', code: 'UA', dial_code: '+380', emoji: '🇺🇦', maxLength: 9 },
  { name: 'Poland', code: 'PL', dial_code: '+48', emoji: '🇵🇱', maxLength: 9 },
  { name: 'Netherlands', code: 'NL', dial_code: '+31', emoji: '🇳🇱', maxLength: 9 },
  { name: 'Belgium', code: 'BE', dial_code: '+32', emoji: '🇧🇪', maxLength: 9 },
  { name: 'Sweden', code: 'SE', dial_code: '+46', emoji: '🇸🇪', maxLength: 9 },
  { name: 'Norway', code: 'NO', dial_code: '+47', emoji: '🇳🇴', maxLength: 8 },
  { name: 'Denmark', code: 'DK', dial_code: '+45', emoji: '🇩🇰', maxLength: 8 },
  { name: 'Finland', code: 'FI', dial_code: '+358', emoji: '🇫🇮', maxLength: 10 },
  { name: 'Switzerland', code: 'CH', dial_code: '+41', emoji: '🇨🇭', maxLength: 9 },
  { name: 'Austria', code: 'AT', dial_code: '+43', emoji: '🇦🇹', maxLength: 10 },
  { name: 'Turkey', code: 'TR', dial_code: '+90', emoji: '🇹🇷', maxLength: 10 },
  { name: 'Saudi Arabia', code: 'SA', dial_code: '+966', emoji: '🇸🇦', maxLength: 9 },
  { name: 'United Arab Emirates', code: 'AE', dial_code: '+971', emoji: '🇦🇪', maxLength: 9 },
  { name: 'South Korea', code: 'KR', dial_code: '+82', emoji: '🇰🇷', maxLength: 10 },
];
